// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type DockerContainer struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	Image  string `json:"image"`
	Uptime string `json:"uptime"`
}

type Game struct {
	HomeTeam  string `json:"homeTeam"`
	AwayTeam  string `json:"awayTeam"`
	HomeScore *int   `json:"homeScore,omitempty"`
	AwayScore *int   `json:"awayScore,omitempty"`
	Status    string `json:"status"`
	Date      string `json:"date"`
}

type Mutation struct {
}

type Query struct {
}

type RedditPost struct {
	Title        string `json:"title"`
	Score        int    `json:"score"`
	CommentCount int    `json:"commentCount"`
	URL          string `json:"url"`
	Author       string `json:"author"`
}

type SportsData struct {
	RecentGames   []*Game `json:"recentGames"`
	UpcomingGames []*Game `json:"upcomingGames"`
}

type SubredditFeed struct {
	Subreddit string        `json:"subreddit"`
	Posts     []*RedditPost `json:"posts"`
}

type YoutubeChannel struct {
	ChannelName string          `json:"channelName"`
	Videos      []*YoutubeVideo `json:"videos"`
}

type YoutubeVideo struct {
	Title        string `json:"title"`
	VideoID      string `json:"videoId"`
	PublishedAt  string `json:"publishedAt"`
	ThumbnailURL string `json:"thumbnailUrl"`
}

type TemperatureUnit string

const (
	TemperatureUnitF TemperatureUnit = "F"
	TemperatureUnitC TemperatureUnit = "C"
)

var AllTemperatureUnit = []TemperatureUnit{
	TemperatureUnitF,
	TemperatureUnitC,
}

func (e TemperatureUnit) IsValid() bool {
	switch e {
	case TemperatureUnitF, TemperatureUnitC:
		return true
	}
	return false
}

func (e TemperatureUnit) String() string {
	return string(e)
}

func (e *TemperatureUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemperatureUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemperatureUnit", str)
	}
	return nil
}

func (e TemperatureUnit) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemperatureUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemperatureUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
