package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"dashboard/db"
	"dashboard/graph/model"
	"dashboard/widgets"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/99designs/gqlgen/graphql"
)

// UpdateWidgetConfig is the resolver for the updateWidgetConfig field.
func (r *mutationResolver) UpdateWidgetConfig(ctx context.Context, id int, config map[string]any, position *int) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.UpdateConfig(ctx, id, config, position)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// ToggleWidget is the resolver for the toggleWidget field.
func (r *mutationResolver) ToggleWidget(ctx context.Context, id int, enabled bool) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.SetEnabled(ctx, id, enabled)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// Widgets is the resolver for the widgets field.
func (r *queryResolver) Widgets(ctx context.Context) ([]*db.WidgetConfig, error) {
	return r.WidgetRepo.List(ctx)
}

// WeatherData is the resolver for the weatherData field.
func (r *queryResolver) WeatherData(ctx context.Context, lat float64, lon float64, unit *model.TemperatureUnit, location *string) (*widgets.WeatherData, error) {
	u := model.TemperatureUnitF
	if unit != nil {
		u = *unit
	}
	data, err := r.fetchWeather(ctx, lat, lon, string(u))
	if err != nil {
		return nil, err
	}
	if location != nil {
		data.Location = *location
	}
	return data, nil
}

// SportsData is the resolver for the sportsData field.
func (r *queryResolver) SportsData(ctx context.Context, sport string, teamIds []string) (*widgets.SportsData, error) {
	sport = strings.ToLower(sport)
	data, err := r.fetchScoreboard(ctx, sport)
	if err != nil || len(teamIds) == 0 {
		return data, err
	}
	hasAny := func(g *widgets.Game) bool {
		return slices.ContainsFunc(teamIds, g.HasTeam)
	}
	filtered := &widgets.SportsData{Week: data.Week, RecentGames: []*widgets.Game{}, UpcomingGames: []*widgets.Game{}}
	for _, g := range data.RecentGames {
		if hasAny(g) {
			filtered.RecentGames = append(filtered.RecentGames, g)
		}
	}
	for _, g := range data.UpcomingGames {
		if hasAny(g) {
			filtered.UpcomingGames = append(filtered.UpcomingGames, g)
		}
	}
	return filtered, nil
}

// TeamSchedule is the resolver for the teamSchedule field.
func (r *queryResolver) TeamSchedule(ctx context.Context, sport string, teamID string) (*widgets.TeamSchedule, error) {
	id, err := widgets.NormalizeTeamID(teamID)
	if err != nil {
		return nil, err
	}
	return r.fetchTeamSchedule(ctx, strings.ToLower(sport), id)
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, sport string) ([]*widgets.StandingsConference, error) {
	return r.fetchStandings(ctx, strings.ToLower(sport))
}

// RedditData is the resolver for the redditData field.
func (r *queryResolver) RedditData(ctx context.Context, subreddits []string) ([]*widgets.SubredditFeed, error) {
	// Fetched one at a time: Reddit rate-limits bursts of anonymous requests.
	feeds := make([]*widgets.SubredditFeed, 0, len(subreddits))
	for _, s := range subreddits {
		name, err := widgets.NormalizeSubreddit(s)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		feed, err := r.fetchSubreddit(ctx, name)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		feeds = append(feeds, feed)
	}
	return feeds, nil
}

// YoutubeData is the resolver for the youtubeData field.
func (r *queryResolver) YoutubeData(ctx context.Context, channelIds []string) ([]*model.YoutubeChannel, error) {
	return nil, errors.New("YoutubeData: not implemented yet")
}

// DockerData is the resolver for the dockerData field.
func (r *queryResolver) DockerData(ctx context.Context) ([]*widgets.DockerContainer, error) {
	if r.Docker == nil {
		return nil, errors.New("docker: client not available")
	}
	return r.Docker.Containers(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
