package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"dashboard/db"
	"dashboard/graph/model"
	"dashboard/widgets"
	"errors"
	"fmt"
)

// UpdateWidgetConfig is the resolver for the updateWidgetConfig field.
func (r *mutationResolver) UpdateWidgetConfig(ctx context.Context, id int, config map[string]any, position *int) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.UpdateConfig(ctx, id, config, position)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// ToggleWidget is the resolver for the toggleWidget field.
func (r *mutationResolver) ToggleWidget(ctx context.Context, id int, enabled bool) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.SetEnabled(ctx, id, enabled)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// Widgets is the resolver for the widgets field.
func (r *queryResolver) Widgets(ctx context.Context) ([]*db.WidgetConfig, error) {
	return r.WidgetRepo.List(ctx)
}

// WeatherData is the resolver for the weatherData field.
func (r *queryResolver) WeatherData(ctx context.Context, lat float64, lon float64, unit *model.TemperatureUnit, location *string) (*widgets.WeatherData, error) {
	u := model.TemperatureUnitF
	if unit != nil {
		u = *unit
	}
	data, err := r.fetchWeather(ctx, lat, lon, string(u))
	if err != nil {
		return nil, err
	}
	if location != nil {
		data.Location = *location
	}
	return data, nil
}

// SportsData is the resolver for the sportsData field.
func (r *queryResolver) SportsData(ctx context.Context, sport string, teamIds []string) (*model.SportsData, error) {
	return nil, errors.New("SportsData: not implemented yet")
}

// RedditData is the resolver for the redditData field.
func (r *queryResolver) RedditData(ctx context.Context, subreddits []string) ([]*model.SubredditFeed, error) {
	return nil, errors.New("RedditData: not implemented yet")
}

// YoutubeData is the resolver for the youtubeData field.
func (r *queryResolver) YoutubeData(ctx context.Context, channelIds []string) ([]*model.YoutubeChannel, error) {
	return nil, errors.New("YoutubeData: not implemented yet")
}

// DockerData is the resolver for the dockerData field.
func (r *queryResolver) DockerData(ctx context.Context) ([]*model.DockerContainer, error) {
	return nil, errors.New("DockerData: not implemented yet")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
