package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"dashboard/backgrounds"
	"dashboard/db"
	"dashboard/graph/model"
	"dashboard/widgets"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/99designs/gqlgen/graphql"
)

// UpdateWidgetConfig is the resolver for the updateWidgetConfig field.
func (r *mutationResolver) UpdateWidgetConfig(ctx context.Context, id int, config map[string]any, position *int) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.UpdateConfig(ctx, id, config, position)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// ToggleWidget is the resolver for the toggleWidget field.
func (r *mutationResolver) ToggleWidget(ctx context.Context, id int, enabled bool) (*db.WidgetConfig, error) {
	w, err := r.WidgetRepo.SetEnabled(ctx, id, enabled)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("widget %d not found", id)
	}
	return w, err
}

// CreatePlaylist is the resolver for the createPlaylist field.
func (r *mutationResolver) CreatePlaylist(ctx context.Context, name string) (*db.Playlist, error) {
	return r.Music.CreatePlaylist(ctx, name)
}

// RenamePlaylist is the resolver for the renamePlaylist field.
func (r *mutationResolver) RenamePlaylist(ctx context.Context, id int, name string) (*db.Playlist, error) {
	p, err := r.Music.RenamePlaylist(ctx, id, name)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("playlist %d not found", id)
	}
	return p, err
}

// SetPlaylistTheme is the resolver for the setPlaylistTheme field.
func (r *mutationResolver) SetPlaylistTheme(ctx context.Context, id int, theme *string) (*db.Playlist, error) {
	name := ""
	if theme != nil {
		name = *theme
		ok, err := backgrounds.Exists(r.BackgroundsDir, name)
		if err != nil {
			return nil, err
		}
		if !ok {
			return nil, fmt.Errorf("no background theme named %q", name)
		}
	}
	p, err := r.Music.SetTheme(ctx, id, name)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("playlist %d not found", id)
	}
	return p, err
}

// DeletePlaylist is the resolver for the deletePlaylist field.
func (r *mutationResolver) DeletePlaylist(ctx context.Context, id int) (bool, error) {
	err := r.Music.DeletePlaylist(ctx, id)
	if errors.Is(err, db.ErrNotFound) {
		return false, fmt.Errorf("playlist %d not found", id)
	}
	return err == nil, err
}

// AddSong is the resolver for the addSong field.
func (r *mutationResolver) AddSong(ctx context.Context, playlistID int, url string) (*db.Song, error) {
	song, err := r.Music.AddSong(ctx, playlistID, url)
	if errors.Is(err, db.ErrNotFound) {
		return nil, fmt.Errorf("playlist %d not found", playlistID)
	}
	return song, err
}

// RemoveSong is the resolver for the removeSong field.
func (r *mutationResolver) RemoveSong(ctx context.Context, id int) (bool, error) {
	err := r.Music.RemoveSong(ctx, id)
	if errors.Is(err, db.ErrNotFound) {
		return false, fmt.Errorf("song %d not found", id)
	}
	return err == nil, err
}

// Widgets is the resolver for the widgets field.
func (r *queryResolver) Widgets(ctx context.Context) ([]*db.WidgetConfig, error) {
	return r.WidgetRepo.List(ctx)
}

// WeatherData is the resolver for the weatherData field.
func (r *queryResolver) WeatherData(ctx context.Context, lat float64, lon float64, unit *model.TemperatureUnit, location *string) (*widgets.WeatherData, error) {
	u := model.TemperatureUnitF
	if unit != nil {
		u = *unit
	}
	data, err := r.fetchWeather(ctx, lat, lon, string(u))
	if err != nil {
		return nil, err
	}
	if location != nil {
		data.Location = *location
	}
	return data, nil
}

// SportsData is the resolver for the sportsData field.
func (r *queryResolver) SportsData(ctx context.Context, sport string, teamIds []string) (*widgets.SportsData, error) {
	sport = strings.ToLower(sport)
	data, err := r.fetchScoreboard(ctx, sport)
	if err != nil || len(teamIds) == 0 {
		return data, err
	}
	hasAny := func(g *widgets.Game) bool {
		return slices.ContainsFunc(teamIds, g.HasTeam)
	}
	filtered := &widgets.SportsData{Week: data.Week, RecentGames: []*widgets.Game{}, UpcomingGames: []*widgets.Game{}}
	for _, g := range data.RecentGames {
		if hasAny(g) {
			filtered.RecentGames = append(filtered.RecentGames, g)
		}
	}
	for _, g := range data.UpcomingGames {
		if hasAny(g) {
			filtered.UpcomingGames = append(filtered.UpcomingGames, g)
		}
	}
	return filtered, nil
}

// TeamSchedule is the resolver for the teamSchedule field.
func (r *queryResolver) TeamSchedule(ctx context.Context, sport string, teamID string) (*widgets.TeamSchedule, error) {
	id, err := widgets.NormalizeTeamID(teamID)
	if err != nil {
		return nil, err
	}
	return r.fetchTeamSchedule(ctx, strings.ToLower(sport), id)
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, sport string) ([]*widgets.StandingsConference, error) {
	return r.fetchStandings(ctx, strings.ToLower(sport))
}

// RedditData is the resolver for the redditData field.
func (r *queryResolver) RedditData(ctx context.Context, subreddits []string) ([]*widgets.SubredditFeed, error) {
	// Fetched one at a time: Reddit rate-limits bursts of anonymous requests.
	feeds := make([]*widgets.SubredditFeed, 0, len(subreddits))
	for _, s := range subreddits {
		name, err := widgets.NormalizeSubreddit(s)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		feed, err := r.fetchSubreddit(ctx, name)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		feeds = append(feeds, feed)
	}
	return feeds, nil
}

// YoutubeData is the resolver for the youtubeData field.
func (r *queryResolver) YoutubeData(ctx context.Context, channelIds []string) ([]*widgets.YoutubeChannel, error) {
	channels := make([]*widgets.YoutubeChannel, 0, len(channelIds))
	for _, id := range channelIds {
		ref, err := widgets.NormalizeYouTubeChannel(id)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		channel, err := r.fetchYouTubeChannel(ctx, ref)
		if err != nil {
			graphql.AddError(ctx, err)
			continue
		}
		channels = append(channels, channel)
	}
	return channels, nil
}

// DockerData is the resolver for the dockerData field.
func (r *queryResolver) DockerData(ctx context.Context) ([]*widgets.DockerContainer, error) {
	if r.Docker == nil {
		return nil, errors.New("docker: client not available")
	}
	return r.Docker.Containers(ctx)
}

// Playlists is the resolver for the playlists field.
func (r *queryResolver) Playlists(ctx context.Context) ([]*db.Playlist, error) {
	return r.Music.Playlists(ctx)
}

// BackgroundThemes is the resolver for the backgroundThemes field.
func (r *queryResolver) BackgroundThemes(ctx context.Context) ([]*backgrounds.BackgroundTheme, error) {
	if r.BackgroundsDir == "" {
		return []*backgrounds.BackgroundTheme{}, nil
	}
	return backgrounds.List(r.BackgroundsDir, "/backgrounds")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
